// Auto-generated by OpenLane
module cache_controller(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  inout vccd1,
  inout vssd1,
  input clk,
  input reset,
  input cpu_read,
  input cpu_write,
  input[31:0] cpu_addr,
  input[63:0] cpu_wdata,
  output[63:0] cpu_rdata,
  output cpu_ready,
  input[63:0] mem_rdata,
  input mem_ready,
  output mem_read,
  output mem_write,
  output[31:0] mem_addr,
  output[63:0] mem_wdata
);
endmodule
